# Generated by Django 2.2.4 on 2019-09-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190911_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(default='1', on_delete=1, to='app01.UserGroup'),
            preserve_default=False,
        ),
    ]
