# Generated by Django 2.2.4 on 2019-09-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserGroup'),
        ),
    ]
